Read in all years and merge as final processing step for data_analysis

In [3]:
import pandas as pd

# TODO Read in files into dataframes
merge_folder = "files/output/"

# add as many dfs as you want to merge
df_1_file_name = "merge_2023-eea_europa_eu-CarsCO2.csv"
# read in file
df_1 = pd.read_csv(merge_folder+df_1_file_name)

# df_2_file_name = "merge_2022-eea_europa_eu-CarsCO2.csv"
# read in file
# df_2 = pd.read_csv(merge_folder+df_2_file_name)

In [4]:
# TODO do merge dataframes magic
df_1.head(5)

,Unnamed: 0,category_of_vehicle,fuel_type,id,mass_vehicle,engine_capacity,engine_power,year,electric_energy_consumption,fuel_consumption,specific_co2_emissions
0,0,M1,petrol,132193881,1345.0,1498.0,110.0,2023,NaN,6.3,143.0
1,1,M1,petrol,132193882,1425.0,1469.0,96.0,2023,NaN,5.2,118.0
2,2,M1,petrol,132193883,1496.0,999.0,81.0,2023,NaN,6.6,150.0
3,3,M1,electric,132193884,1440.0,NaN,135.0,2023,157.0,NaN,0.0
4,4,M1,electric,132193885,2239.0,NaN,220.0,2023,179.0,NaN,0.0

In [ ]:
# TODO export merged file